version: "3.7"

services:
  database:
    container_name: postgres-user-page
    image: postgres:13.4-buster
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    environment:
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data

